Repository varbhat/exatorrent, pull requests merged in 2023-11, with the labels that each got.

#402 fix: typo
  internal/core/engine.go
Labels: documentation

#405 feat(ci): use docker bake to build binaries
  .github/workflows/docker.yml
  Dockerfile
  Makefile
  docker-bake.hcl
Labels: enhancement, github_actions

#424 fix(ci): build docker and binaries
  .github/workflows/docker.yml
  Dockerfile
  docker-bake.hcl
Labels: bug

#426 feat(sqlite): abandon crawshaw.io/sqlite
  .github/workflows/docker.yml
  Makefile
  go.mod
  go.sum
  internal/db/sqlite3filestatedb.go
  internal/db/sqlite3lockstatedb.go
  internal/db/sqlite3pc.go
  internal/db/sqlite3torrentdb.go
  internal/db/sqlite3torrentuserdb.go
  internal/db/sqlite3trackerdb.go
  internal/db/sqlite3userdb.go
Labels: bug, enhancement
